name: faker_dart
description: generate massive amounts of fake data in Dart & Flutter! A dart
  port of the famous faker.js
version: 0.2.2
homepage: https://github.com/casvanluijtelaar/faker.dart
repository: https://github.com/casvanluijtelaar/faker.dart

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  collection: ^1.18.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
