name: faker_dart
description: generate massive amounts of fake data in Dart & Flutter! A dart
  port of the famous faker.js
version: 0.1.8
homepage: https://github.com/casvanluijtelaar/faker.dart
repository: https://github.com/casvanluijtelaar/faker.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.16.0

dev_dependencies:
  mocktail: ^0.2.0
  test: ^1.19.5
  very_good_analysis: ^2.1.2
