name: faker_dart
description: generate massive amounts of fake data in dart and flutter
version: 0.0.1-dev.1
homepage: https://github.com/casvanluijtelaar/faker.dart

environment:
  sdk: ">=2.12.0 <3.0.0"
